### ISSUE TITLE
recordtrigger does not write values correctly

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#318]
The eegsynth implementation seems to assume single numeric values, but in the biochill game codes it as channel.position="(x, y, z)", i.e. three values joined together in a string. Also, some biochill events have a textual value, such as BeatTrigger="ExitBeatArea BusMovesA"

**Comment by robertoostenveld** [comment]
I just pushed a small code update that I already made last week, but that I have not tested yet.

mac011> git commit -a
[master 15bd2de] allow redis messages with string values to be recorded to tsv file
 1 file changed, 7 insertions(+), 4 deletions(-)

mac011> git push
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 631 bytes | 631.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:eegsynth/eegsynth.git
   65044ba..15bd2de  master -> master

**Comment by robertoostenveld** [comment]
I tested it, there is one error on line 105
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./recordtrigger.py", line 105, in run
    print(("%s\t%d\t%s" % (self.redischannel, val, timestamp)))
```

the debugging line expects the value as a string, not as a number.

**Comment by robertoostenveld** [comment]
@ JohnDoenut please check the code updates
