### ISSUE TITLE
update pyqtgraph from 0.12 to latest version 

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#424]
The pyqtgraph dependency is now fixed in setup.py at version 0.12 as version 0.13 causes errors due to the interaction between  pyqtgraph and PyQt having changed. 

It would be good to update the code (mainly the plotxxx modules) such that it works with the latest pyqtgraph version. This facilitates installation, prevents errors such as the one detected and fixed in https://github.com/eegsynth/eegsynth/commit/883ac07ce4f306357785f71194625a4391b07a31. It would also make future maintenance and upgrading easier, like migrating to PyQt6.

**Comment by robertoostenveld** [comment]
In a clean eegsynth-installed environment I did 

```
mac036> pip uninstall pyqtgraph
Found existing installation: pyqtgraph 0.12.0
Uninstalling pyqtgraph-0.12.0:
  Would remove:
    /Users/roboos/miniconda3/envs/eegsynth/lib/python3.10/site-packages/pyqtgraph-0.12.0.dist-info/*
    /Users/roboos/miniconda3/envs/eegsynth/lib/python3.10/site-packages/pyqtgraph/*
Proceed (Y/n)? y
  Successfully uninstalled pyqtgraph-0.12.0

mac036> pip install pyqtgraph==0.13
eegsynth 0.7.6 requires pyqtgraph==0.12, but you have pyqtgraph 0.13.0 which is incompatible.
Successfully installed pyqtgraph-0.13.0
```

This gives the error
```
Traceback (most recent call last):
  File "/Users/roboos/miniconda3/envs/eegsynth/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/roboos/miniconda3/envs/eegsynth/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/roboos/eegsynth/bin/eegsynth.py", line 320, in _start_module
    module(args_list)
  File "/Users/roboos/eegsynth/bin/../module/plotsignal/__init__.py", line 14, in __init__
    _start()
  File "/Users/roboos/eegsynth/bin/../module/plotsignal/plotsignal.py", line 143, in _start
    app = QtGui.QApplication(sys.argv)
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'
Exception ignored in: <function _executable.__del__ at 0x7fa7a2a2cf70>
Traceback (most recent call last):
  File "/Users/roboos/eegsynth/bin/../module/plotsignal/__init__.py", line 18, in __del__
    _stop()
  File "/Users/roboos/eegsynth/bin/../module/plotsignal/plotsignal.py", line 278, in _stop
    QtGui.QApplication.quit()
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'
```

**Comment by robertoostenveld** [comment]
Recent versions of [pyqtgraph](https://pypi.org/project/pyqtgraph/) require python>=3.8. Since the plotting of data in EEGsynth is rather fundamental, I will also update the python requirement of eegsynth. It was 2.7 (as that is the one we once started with), I will change that to 3.8. Given that the release of 3.8 was on 14 Oct 2019 and the scheduled end-of-life is 5 years later, the 3.8 is still a current release, whereas any older version is not. 

I'll update some documentation as well, but won't fix all the documentation. There are for example still some references to python 2.
